# Set default language
lang: en

timeFormats:
  second: "second"
  seconds: "seconds"
  minute: "minute"
  minutes: "minutes"
  hour: "hour"
  hours: "hours"
  day: "day"
  days: "days"
  week: "week"
  weeks: "weeks"
