name: Parkour
main: me.cxmilo.parkour.ParkourPlugin
version: 2.0-SNAPSHOT
author: vCamilx
commands:
  lang:
    description: Change user lang
  parkour:
    description: Parkour command
  setup:
    description: Parkour setup command
    aliases: [ps, parkours]